name: tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  tests-all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          check-latest: true
      - run: npm i -g pnpm@latest
      - run: pnpm i --no-frozen-lockfile
      - run: pnpm run test:actions
